
services:
  web:
    image: gammbity/deviceservice:latest
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    volumes:
      - .:/app
    working_dir: /app/backend
    expose:
      - "8000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine

  celery:
    image: python:3.11-slim
    command: >
      sh -c "
        celery -A config worker --loglevel=info
      "
    volumes:
      - .:/app
    working_dir: /app/backend
    depends_on:
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf:ro
    depends_on:
      - web

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   command: tunnel --url http://web:8000
  #   depends_on:
  #     - web
  #   restart: always
