services:
  web:
    build: .
    command: gunicorn backend.config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A backend.config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --url http://web:8000
    depends_on:
      - web
    restart: always
