# Generated by Django 5.2.1 on 2025-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_device_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(choices=[('chernefka', 'Chernefka'), ('sebzor', 'Sebzor'), ('yunsobod', 'Yunsobod')], default='Chernefka', max_length=255, verbose_name='Device Location'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='created', max_length=50, verbose_name='Device Status'),
        ),
    ]
