# Generated by Django 5.2.1 on 2025-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_device_location_alter_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware')], default='Software', max_length=50, verbose_name='Device Type'),
        ),
    ]
